### PR TITLE
Rise integration

### PR DESCRIPTION
**Pull request by dbarker8**

### CODE REVIEW

**Comment by rsimon** [comment]
Looks great - many thanks. Only one thing: I tried to decouple the import dialog(s) & code from the sidebar menu UI. The way I organized things (at the moment...) is that the menu would just fire the event upwards to `App.jsx`, and the the actual uploading (dialog + process) is done through code located in the `operations` folder. Probably the RISEModal could sit in a subfolder of `importing` (as a specific importable data type - we'll have more in the future CTS, TEI from TextGrid).

**Comment by rsimon** [comment]
At least, the component shouldn't sit under `common` - that's for components that appear both in the workspace UI and the public profile (the UI you see when visiting someone else's workspace). But I'm happy to make those changes. (Will be travelling next week, but should have some time in between.)

**Comment by dbarker8** [comment]
Rainer,

I can go and make those changes, I think I have a decent understanding of your apps organization structure now - I was just trying to get a basic connection working first. Or, let me know if you’d prefer to do it.

Best,
______________________________
Dean Barker
www.deanbarkerweb.com
330-212-0070

**Comment by rsimon** [comment]
Perfect - do feel free to go ahead and make the changes. I can tweak things in case anything should be needed afterwards. Thanks!

**Pull request merged**
